/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.business_managment_system.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Happy Go Lucky
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
     private Timer tmrTime;
    
    public Admin() {
        initComponents();
        setTime();
        lblCustOrUp.setVisible(false);
        
        lblCusUp.setVisible(false);
        lblSupOrUp.setVisible(false);
        lblAddItemsToStockUp.setVisible(false);
        lblSupUp.setVisible(false);
        lblViewStUp.setVisible(false);
        lblManStUp.setVisible(false);
        lblViewRepUp.setVisible(false);
        lblManUserUp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblViewRepUp = new javax.swing.JLabel();
        lblCustOrUp = new javax.swing.JLabel();
        lblCusUp = new javax.swing.JLabel();
        lblSupUp = new javax.swing.JLabel();
        lblAddItemsToStockUp = new javax.swing.JLabel();
        lblSupOrUp = new javax.swing.JLabel();
        lblViewStUp = new javax.swing.JLabel();
        lblManStUp = new javax.swing.JLabel();
        lblSupTxt = new javax.swing.JLabel();
        lblManUserTxt = new javax.swing.JLabel();
        lblSupOrTxt = new javax.swing.JLabel();
        lblItemToStockTxt = new javax.swing.JLabel();
        lblViewStTxt = new javax.swing.JLabel();
        lblManItemTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCustOrtxt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCusTxt = new javax.swing.JLabel();
        lblCus = new javax.swing.JLabel();
        lblSup = new javax.swing.JLabel();
        lblCustOr = new javax.swing.JLabel();
        lblViewSt = new javax.swing.JLabel();
        lblViewRepTxt = new javax.swing.JLabel();
        lblViewRep = new javax.swing.JLabel();
        lblAddItemsToStock = new javax.swing.JLabel();
        lblManUserUp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMangeUser = new javax.swing.JLabel();
        lblManSt = new javax.swing.JLabel();
        lblSupOr = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Home");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 210, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 290, 40));

        lblViewRepUp.setBackground(new java.awt.Color(255, 255, 255));
        lblViewRepUp.setOpaque(true);
        jPanel1.add(lblViewRepUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 380, 10));

        lblCustOrUp.setBackground(new java.awt.Color(255, 255, 255));
        lblCustOrUp.setOpaque(true);
        jPanel1.add(lblCustOrUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 380, 10));

        lblCusUp.setBackground(new java.awt.Color(255, 255, 255));
        lblCusUp.setOpaque(true);
        jPanel1.add(lblCusUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 380, 10));

        lblSupUp.setBackground(new java.awt.Color(255, 255, 255));
        lblSupUp.setOpaque(true);
        jPanel1.add(lblSupUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 380, 10));

        lblAddItemsToStockUp.setBackground(new java.awt.Color(255, 255, 255));
        lblAddItemsToStockUp.setOpaque(true);
        jPanel1.add(lblAddItemsToStockUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 380, 10));

        lblSupOrUp.setBackground(new java.awt.Color(255, 255, 255));
        lblSupOrUp.setOpaque(true);
        jPanel1.add(lblSupOrUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 380, 10));

        lblViewStUp.setBackground(new java.awt.Color(255, 255, 255));
        lblViewStUp.setOpaque(true);
        jPanel1.add(lblViewStUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 380, 10));

        lblManStUp.setBackground(new java.awt.Color(255, 255, 255));
        lblManStUp.setOpaque(true);
        jPanel1.add(lblManStUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 380, 10));

        lblSupTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblSupTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupTxt.setText("Manage Suppliers");
        jPanel1.add(lblSupTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 320, 30));

        lblManUserTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblManUserTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManUserTxt.setText("Manage User");
        jPanel1.add(lblManUserTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 660, 320, 30));

        lblSupOrTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblSupOrTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupOrTxt.setText("Make Supplier Order");
        jPanel1.add(lblSupOrTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 320, 30));

        lblItemToStockTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblItemToStockTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemToStockTxt.setText("Add GRN");
        jPanel1.add(lblItemToStockTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 320, 30));

        lblViewStTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblViewStTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewStTxt.setText("View Stock");
        jPanel1.add(lblViewStTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 320, 30));

        lblManItemTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblManItemTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManItemTxt.setText("Manage Items");
        jPanel1.add(lblManItemTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 320, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/33752282-L-uomo-in-hotel-il-check-in-presso-la-reception-o-front-office-viene-data-carta-chiave-Archivio-Fotografico copy.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, 140));

        lblCustOrtxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblCustOrtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustOrtxt.setText("Make Customer Order");
        jPanel1.add(lblCustOrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 320, 30));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/sciquest-eprocurement-supplier-risk-management-mitigation-vendor-automated copy.jpg"))); // NOI18N
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 360, 140));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/fffffffff copy.jpg"))); // NOI18N
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 360, 140));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/pic6 copy.jpg"))); // NOI18N
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 360, 140));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/pic5 copy.jpg"))); // NOI18N
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 360, 140));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/Female-inventory-manager-tracking-inventory-on-an-iPad-e1448989000816-750x388 copy.jpg"))); // NOI18N
        jLabel18.setOpaque(true);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 360, 140));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/suppliers copy.jpg"))); // NOI18N
        jLabel19.setOpaque(true);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 355, 140));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/pics/Customer-Segmentation-e1416295708167cc.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 360, 140));

        lblCusTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblCusTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCusTxt.setText("Manage Customers");
        jPanel1.add(lblCusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 320, 30));

        lblCus.setBackground(new java.awt.Color(255, 255, 255));
        lblCus.setOpaque(true);
        lblCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCusMouseExited(evt);
            }
        });
        jPanel1.add(lblCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 380, 180));

        lblSup.setBackground(new java.awt.Color(255, 255, 255));
        lblSup.setOpaque(true);
        lblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupMouseExited(evt);
            }
        });
        jPanel1.add(lblSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 380, 180));

        lblCustOr.setBackground(new java.awt.Color(255, 255, 255));
        lblCustOr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustOr.setOpaque(true);
        lblCustOr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblCustOrFocusGained(evt);
            }
        });
        lblCustOr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustOrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustOrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustOrMouseExited(evt);
            }
        });
        lblCustOr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblCustOrKeyPressed(evt);
            }
        });
        jPanel1.add(lblCustOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 380, 180));

        lblViewSt.setBackground(new java.awt.Color(255, 255, 255));
        lblViewSt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewSt.setOpaque(true);
        lblViewSt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewStMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewStMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewStMouseExited(evt);
            }
        });
        jPanel1.add(lblViewSt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 380, 180));

        lblViewRepTxt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblViewRepTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewRepTxt.setText("View Reports");
        jPanel1.add(lblViewRepTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 660, 320, 30));

        lblViewRep.setBackground(new java.awt.Color(255, 255, 255));
        lblViewRep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewRep.setOpaque(true);
        lblViewRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewRepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewRepMouseExited(evt);
            }
        });
        jPanel1.add(lblViewRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 380, 180));

        lblAddItemsToStock.setBackground(new java.awt.Color(255, 255, 255));
        lblAddItemsToStock.setOpaque(true);
        lblAddItemsToStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddItemsToStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddItemsToStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddItemsToStockMouseExited(evt);
            }
        });
        jPanel1.add(lblAddItemsToStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 380, 180));

        lblManUserUp.setBackground(new java.awt.Color(255, 255, 255));
        lblManUserUp.setOpaque(true);
        jPanel1.add(lblManUserUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, 380, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/pics/crm-930x620 copy.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 360, 140));

        lblMangeUser.setBackground(new java.awt.Color(255, 255, 255));
        lblMangeUser.setOpaque(true);
        lblMangeUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMangeUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMangeUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMangeUserMouseExited(evt);
            }
        });
        jPanel1.add(lblMangeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 380, 180));

        lblManSt.setBackground(new java.awt.Color(255, 255, 255));
        lblManSt.setOpaque(true);
        lblManSt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManStMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManStMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManStMouseExited(evt);
            }
        });
        jPanel1.add(lblManSt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 380, 180));

        lblSupOr.setBackground(new java.awt.Color(255, 255, 255));
        lblSupOr.setOpaque(true);
        lblSupOr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupOrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupOrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupOrMouseExited(evt);
            }
        });
        jPanel1.add(lblSupOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 380, 180));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 204));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 240, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(">");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel22.setOpaque(true);
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 20));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Move");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 50, 20));

        lblLogout.setBackground(new java.awt.Color(255, 0, 0));
        lblLogout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("LogOut");
        lblLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel3.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 130, 20));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("V");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel28.setOpaque(true);
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 50, 20));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("/\\");
            jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
            jLabel29.setOpaque(true);
            jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 20));

            jLabel30.setBackground(new java.awt.Color(0, 0, 0));
            jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel30.setForeground(new java.awt.Color(255, 255, 255));
            jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel30.setText("<");
            jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
            jLabel30.setOpaque(true);
            jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 20));

            jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
            jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel31.setText("Select");
            jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 50, 20));

            jLabel24.setBackground(new java.awt.Color(0, 0, 0));
            jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
            jLabel24.setForeground(new java.awt.Color(255, 255, 255));
            jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel24.setText("Enter");
            jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
            jLabel24.setOpaque(true);
            jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 20));

            jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 1280, -1));

            lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/business_managment_system/view/Pics/4hgiRFC copy.jpg"))); // NOI18N
            jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void lblCustOrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustOrMouseEntered
        lblCustOrUp.setVisible(true);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblCustOrMouseEntered

    private void lblCustOrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustOrMouseExited
        lblCustOrUp.setVisible(false);
        setCursor(null);
    }//GEN-LAST:event_lblCustOrMouseExited

    private void lblCusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMouseEntered
       lblCusUp.setVisible(true);
       setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblCusMouseEntered

    private void lblCusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMouseExited
        lblCusUp.setVisible(false);
        setCursor(null);
    }//GEN-LAST:event_lblCusMouseExited

    private void lblSupOrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrMouseEntered
         lblSupOrUp.setVisible(true);
         setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblSupOrMouseEntered

    private void lblSupOrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrMouseExited
         lblSupOrUp.setVisible(false);
         setCursor(null);
    }//GEN-LAST:event_lblSupOrMouseExited

    private void lblAddItemsToStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemsToStockMouseEntered
         lblAddItemsToStockUp.setVisible(true);
         setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblAddItemsToStockMouseEntered

    private void lblAddItemsToStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemsToStockMouseExited
        lblAddItemsToStockUp.setVisible(false);
        setCursor(null);
    }//GEN-LAST:event_lblAddItemsToStockMouseExited

    private void lblSupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupMouseEntered
        lblSupUp.setVisible(true);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblSupMouseEntered

    private void lblSupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupMouseExited
         lblSupUp.setVisible(false);
         setCursor(null);
    }//GEN-LAST:event_lblSupMouseExited

    private void lblViewStMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewStMouseEntered
        lblViewStUp.setVisible(true);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblViewStMouseEntered

    private void lblViewStMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewStMouseExited
       lblViewStUp.setVisible(false);
       setCursor(null);
    }//GEN-LAST:event_lblViewStMouseExited

    private void lblManStMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManStMouseEntered
        lblManStUp.setVisible(true);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblManStMouseEntered

    private void lblManStMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManStMouseExited
        lblManStUp.setVisible(false);
        setCursor(null);
    }//GEN-LAST:event_lblManStMouseExited

    private void lblViewRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewRepMouseEntered
         lblViewRepUp.setVisible(true);
         setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblViewRepMouseEntered

    private void lblViewRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewRepMouseExited
       lblViewRepUp.setVisible(false);
       setCursor(null);
    }//GEN-LAST:event_lblViewRepMouseExited

    private void lblCustOrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblCustOrKeyPressed
        
    }//GEN-LAST:event_lblCustOrKeyPressed

    private void lblCustOrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustOrMouseClicked
        new CustOrder().setVisible(true);
        
    }//GEN-LAST:event_lblCustOrMouseClicked

    private void lblSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupMouseClicked
          new ManageSupplier().setVisible(true);
       
    }//GEN-LAST:event_lblSupMouseClicked

    private void lblAddItemsToStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemsToStockMouseClicked
         new Grn().setVisible(true);
        
    }//GEN-LAST:event_lblAddItemsToStockMouseClicked

    private void lblSupOrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrMouseClicked
        new SupOrder().setVisible(true);
        
    }//GEN-LAST:event_lblSupOrMouseClicked

    private void lblViewStMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewStMouseClicked
         new ViewStock().setVisible(true);
        
    }//GEN-LAST:event_lblViewStMouseClicked

    private void lblManStMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManStMouseClicked
        new ManageItem().setVisible(true);
        
    }//GEN-LAST:event_lblManStMouseClicked

    private void lblViewRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewRepMouseClicked
       new ViewReport().setVisible(true);
       
    }//GEN-LAST:event_lblViewRepMouseClicked

    private void lblCustOrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblCustOrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCustOrFocusGained

    private void lblCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMouseClicked
       new ManageCustomer().setVisible(true);
    }//GEN-LAST:event_lblCusMouseClicked

    private void lblMangeUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMangeUserMouseEntered
       lblManUserUp.setVisible(true);
         setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lblMangeUserMouseEntered

    private void lblMangeUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMangeUserMouseExited
        lblManUserUp.setVisible(false);
       setCursor(null);
    }//GEN-LAST:event_lblMangeUserMouseExited

    private void lblMangeUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMangeUserMouseClicked
        new ManageUser().setVisible(true);
    }//GEN-LAST:event_lblMangeUserMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        
         int res = JOptionPane.showConfirmDialog(this, " Do You Want Logout ? " );
         if(res==0){
             new Login().setVisible(true);
             this.dispose();
             tmrTime.stop();
         }
       
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAddItemsToStock;
    private javax.swing.JLabel lblAddItemsToStockUp;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCus;
    private javax.swing.JLabel lblCusTxt;
    private javax.swing.JLabel lblCusUp;
    private javax.swing.JLabel lblCustOr;
    private javax.swing.JLabel lblCustOrUp;
    private javax.swing.JLabel lblCustOrtxt;
    private javax.swing.JLabel lblItemToStockTxt;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblManItemTxt;
    private javax.swing.JLabel lblManSt;
    private javax.swing.JLabel lblManStUp;
    private javax.swing.JLabel lblManUserTxt;
    private javax.swing.JLabel lblManUserUp;
    private javax.swing.JLabel lblMangeUser;
    private javax.swing.JLabel lblSup;
    private javax.swing.JLabel lblSupOr;
    private javax.swing.JLabel lblSupOrTxt;
    private javax.swing.JLabel lblSupOrUp;
    private javax.swing.JLabel lblSupTxt;
    private javax.swing.JLabel lblSupUp;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblViewRep;
    private javax.swing.JLabel lblViewRepTxt;
    private javax.swing.JLabel lblViewRepUp;
    private javax.swing.JLabel lblViewSt;
    private javax.swing.JLabel lblViewStTxt;
    private javax.swing.JLabel lblViewStUp;
    // End of variables declaration//GEN-END:variables

    private void setTime() {
        tmrTime=new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    }
}
