/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.business_managment_system.view;

import edu.ijse.business_managment_system.controller.ControllerFactory;
import edu.ijse.business_managment_system.controller.custom.BatchController;
import edu.ijse.business_managment_system.controller.custom.BrandController;
import edu.ijse.business_managment_system.controller.custom.CustomerController;
import edu.ijse.business_managment_system.controller.custom.CustomerOrderController;
import edu.ijse.business_managment_system.controller.custom.CustomerPaymentController;
import edu.ijse.business_managment_system.controller.custom.ItemController;
import edu.ijse.business_managment_system.dto.BatchDTO;
import edu.ijse.business_managment_system.dto.BrandDTO;
import edu.ijse.business_managment_system.view.ManageCustomer;

import edu.ijse.business_managment_system.dto.CustomerDTO;
import edu.ijse.business_managment_system.dto.CustomerOrderDTO;
import edu.ijse.business_managment_system.dto.CustomerOrderDetailDTO;
import edu.ijse.business_managment_system.dto.CustomerPaymentDTO;
import edu.ijse.business_managment_system.dto.ItemDTO;
import edu.ijse.business_managment_system.idgenerator.IDGenerator;
import edu.ijse.business_managment_system.jasper.MyJasperView;
import java.awt.Color;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Happy Go Lucky
 */
public class CustOrder extends javax.swing.JFrame {

     private CustomerController ctrlcustomer;
      private ItemController ctrlItem;
      private BatchController ctrlBatch;
       private CustomerOrderController ctrlCustomerOrder;
        private CustomerPaymentController ctrlCustomerPayment;
        private BrandController ctrlBrand;
        private Timer tmrTime;
     
    public CustOrder() {
        
         ctrlcustomer = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
         ctrlItem = (ItemController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEM);
         ctrlBatch = (BatchController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BATCH);
          ctrlCustomerOrder = (CustomerOrderController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER_ORDER);
           ctrlCustomerPayment = (CustomerPaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER_PAYMENT);
           ctrlBrand = (BrandController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BRAND);
           
        
        initComponents();
         setOrderDate();
         loadCustomerIds();
         loadItemCodes();
         loadOrderId();
         loadPaymentID();
         txtDiscount.setText("0");
         loadKeyListener();
         setTime();
         pnlBack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBackPayment = new javax.swing.JPanel();
        txtBalance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblMakePayment = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtQTY = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtOrderID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        txtModel = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cmbBatch = new javax.swing.JComboBox();
        cmbICode = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblCart = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblMakeOrder = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbCID = new javax.swing.JComboBox();
        txtUnit = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblbackCustOr = new javax.swing.JLabel();
        pnlTime = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackPayment.setPreferredSize(new java.awt.Dimension(500, 500));
        pnlBackPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlBackPayment.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 200, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Payment ID");
        pnlBackPayment.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        txtPaymentID.setEditable(false);
        txtPaymentID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPaymentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlBackPayment.add(txtPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TotalAmount");
        pnlBackPayment.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        txtTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlBackPayment.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Payment");
        pnlBackPayment.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        txtPayment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        pnlBackPayment.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 200, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Balance");
        pnlBackPayment.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 30));

        lblMakePayment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMakePayment.setForeground(new java.awt.Color(255, 255, 255));
        lblMakePayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMakePayment.setText("Make Payment");
        lblMakePayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        lblMakePayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMakePayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakePaymentMouseClicked(evt);
            }
        });
        pnlBackPayment.add(lblMakePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, 30));

        jPanel1.add(pnlBackPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 380, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Make Customer Order");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 420, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Ctrl");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 20));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Manage Customers");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 120, 20));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ecs");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 50, 20));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Back");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 30, 20));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Enter");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel26.setOpaque(true);
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 20));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Select");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 1280, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 1240, 10));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Last Name  :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 100, 30));

        txtQTY.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 170, 30));

        txtLName.setEditable(false);
        txtLName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 320, 30));

        txtOrderID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, 30));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 170, 30));

        txtFName.setEditable(false);
        txtFName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 290, 30));

        txtBrand.setEditable(false);
        txtBrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        jPanel1.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 200, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 1240, 10));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Batch  :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 100, 30));

        txtAmount.setEditable(false);
        txtAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 330, 30));

        txtDiscount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 170, 30));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Batch Id", "Item Name", "Unit Price", "Discount", "Order Qty", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblOrder);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 1160, 220));

        txtModel.setEditable(false);
        txtModel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        jPanel1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 200, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 1240, 10));

        cmbBatch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbBatch.setMaximumRowCount(1000);
        cmbBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBatchActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 170, 30));

        cmbICode.setEditable(true);
        cmbICode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbICode.setMaximumRowCount(1000);
        cmbICode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbICodeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbICode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Order QTY :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 100, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Total Amount :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 100, 30));

        lblCart.setBackground(new java.awt.Color(51, 255, 0));
        lblCart.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblCart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCart.setText("Add To Cart");
        lblCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        lblCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCart.setOpaque(true);
        lblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCartMouseClicked(evt);
            }
        });
        jPanel1.add(lblCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 340, 120, 30));

        lblRemove.setBackground(new java.awt.Color(255, 0, 0));
        lblRemove.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Remove");
        lblRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRemove.setOpaque(true);
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
        });
        jPanel1.add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 60, 20));

        lblMakeOrder.setBackground(new java.awt.Color(51, 255, 0));
        lblMakeOrder.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblMakeOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMakeOrder.setText("Make Order");
        lblMakeOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        lblMakeOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMakeOrder.setOpaque(true);
        lblMakeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakeOrderMouseClicked(evt);
            }
        });
        jPanel1.add(lblMakeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 620, 180, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Barnd :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 100, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ICode :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CID :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 100, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("First Name :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 100, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Date :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Model :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 240, 100, 30));

        cmbCID.setEditable(true);
        cmbCID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbCID.setMaximumRowCount(1000);
        cmbCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCIDActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 30));

        txtUnit.setEditable(false);
        txtUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 170, 30));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Unit Price :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Order ID :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Discount :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, 30));

        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 130, 1250, 535));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New Customer Order");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 280, 30));

        lblbackCustOr.setBackground(new java.awt.Color(153, 0, 153));
        lblbackCustOr.setOpaque(true);
        jPanel1.add(lblbackCustOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1260, 570));

        pnlTime.setBackground(new java.awt.Color(255, 255, 255));
        pnlTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 204));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlTime.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jPanel1.add(pnlTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 290, 50));

        lblBack.setBackground(new java.awt.Color(102, 102, 102));
        lblBack.setOpaque(true);
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
      Back();
        
    }//GEN-LAST:event_jLabel24MouseClicked

    private void cmbBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBatchActionPerformed
         try {
            String bid=(String)cmbBatch.getSelectedItem();
            BatchDTO batch=ctrlBatch.search(bid);
            txtUnit.setText(""+batch.getUnitPrice());
            
        } catch (Exception ex) {
            //Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbBatchActionPerformed

    private void cmbICodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbICodeActionPerformed
       try {
            String code=(String)cmbICode.getSelectedItem();
            ItemDTO item=ctrlItem.search(code);
            txtModel.setText(item.getModel());
           String bid= (item.getBrand());
           BrandDTO brand = ctrlBrand.search(bid);
            txtBrand.setText(brand.getBrandName());
            
            loadBatchID(code);
            
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_cmbICodeActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        ManageCustomer();
       
    }//GEN-LAST:event_jLabel21MouseClicked

    private void cmbCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCIDActionPerformed
         try {
            String cid=(String)cmbCID.getSelectedItem();
            CustomerDTO customer=ctrlcustomer.search(cid);
            txtFName.setText(customer.getFisrtName());
             txtLName.setText(customer.getLastName());
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCIDActionPerformed
        double totalAmount;
    private void lblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCartMouseClicked
      
         boolean isCheck=Check();
            if(isCheck){
        
                    String itemCode=(String)cmbICode.getSelectedItem();
                    DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
                    String batch=(String) cmbBatch.getSelectedItem();
                    String model=txtModel.getText();
                    double unitPrice=Double.parseDouble(txtUnit.getText());
                    double discount=Double.parseDouble(txtDiscount.getText());
                    int Qty=Integer.parseInt(txtQTY.getText());
                   


                        for(int i=0;i<dtm.getRowCount();i++){
                            String code=(String)dtm.getValueAt(i,0);
                            if(itemCode.equals(code)){
                                int qty=(int)dtm.getValueAt(i,5);	
                                Qty+=qty;
                                dtm.removeRow(i);
                                totalAmount-=qty*(unitPrice-discount);
                            }
                        }
                        double amount=(unitPrice-discount)*Qty;

                         totalAmount+=amount;
                        txtAmount.setText(""+totalAmount);


                        Object[] rowData={itemCode,batch,model,unitPrice,discount,Qty,amount};	
                        dtm.addRow(rowData);

                         txtQTY.setText("");
                         txtDiscount.setText("0");
                         
             }else{
                 JOptionPane.showMessageDialog(this, "Check Again, And Input Validate Data To Proceed. ", "Error", JOptionPane.ERROR_MESSAGE);
            } 
                
    }//GEN-LAST:event_lblCartMouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked
        DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
				int index=tblOrder.getSelectedRow();
                                double amount=(double)dtm.getValueAt(index,6);
				dtm.removeRow(index);
				totalAmount-=amount;
				txtAmount.setText(""+totalAmount); 
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblMakeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeOrderMouseClicked
        DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
        String orderId=txtOrderID.getText();
        String cid=(String) cmbCID.getSelectedItem();
        String date = txtDate.getText();
        
        CustomerOrderDTO customerOrderDTO = new CustomerOrderDTO(orderId,cid,date);
        
        ArrayList<CustomerOrderDetailDTO> allCustomerOrderDetails = new ArrayList<>();
        
        for(int i=0;i<dtm.getRowCount();i++){
            CustomerOrderDetailDTO CustomerOrderDetail = new CustomerOrderDetailDTO(
                    txtOrderID.getText(),
                    dtm.getValueAt(i, 0).toString(),
                    dtm.getValueAt(i, 1).toString(),
                    Double.parseDouble(dtm.getValueAt(i, 3).toString()),
                    Double.parseDouble(dtm.getValueAt(i, 4).toString()),
                    Integer.parseInt(dtm.getValueAt(i, 5).toString()));
                    
            allCustomerOrderDetails.add(CustomerOrderDetail);
        }
        
        try {
            boolean result = ctrlCustomerOrder.add(customerOrderDTO, allCustomerOrderDetails);
            if (result){
                JOptionPane.showMessageDialog(this, "Order has been successfully placed","Success",JOptionPane.INFORMATION_MESSAGE);
                
                pnlBackPayment.setVisible(true);
                txtTotal.setText(""+totalAmount);
                 
            }else{
                JOptionPane.showMessageDialog(this, "Failed to place the Order", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to place the Order", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(CustOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_lblMakeOrderMouseClicked
            double pay;
        double balance;
    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        
        pay=Double.parseDouble( txtPayment.getText());
        
        if(pay>=totalAmount){
            balance=pay-totalAmount;
            txtBalance.setText(""+balance);
            
        }
        
    }//GEN-LAST:event_txtPaymentActionPerformed

    private void lblMakePaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakePaymentMouseClicked
       String cpid=txtPaymentID.getText();
            String oid = txtOrderID.getText();
            double fullAmount =Double.parseDouble(txtTotal.getText()) ;
            double payedAmount = fullAmount;
            String date = txtDate.getText();
            

            CustomerPaymentDTO customerPaymentDTO = new CustomerPaymentDTO(cpid,oid,fullAmount,payedAmount,date);
            try{
                boolean isAdded=ctrlCustomerPayment.add(customerPaymentDTO);
            if(isAdded){
                JOptionPane.showMessageDialog(CustOrder.this,"payment Added Successfully");
                 printReport();
                 DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
                 dtm.setRowCount(0);
                 loadOrderId();
                 pnlBackPayment.setVisible(false);
                 loadPaymentID();
                 txtAmount.setText("");
                
            }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(CustOrder.this,e);
            }catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(CustOrder.this,e);
            } catch (Exception ex) {
                  Logger.getLogger(CustOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_lblMakePaymentMouseClicked

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbBatch;
    private javax.swing.JComboBox cmbCID;
    private javax.swing.JComboBox cmbICode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCart;
    private javax.swing.JLabel lblMakeOrder;
    private javax.swing.JLabel lblMakePayment;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblbackCustOr;
    private javax.swing.JPanel pnlBackPayment;
    private javax.swing.JPanel pnlTime;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables

    private void setOrderDate() {
        java.util.Date d1=new java.util.Date();
		SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
		String formatDate=df.format(d1);
		txtDate.setText(formatDate);
    }

  

   
    private void loadCustomerIds() {
        String cid = null;
        try {
            ArrayList<CustomerDTO> allcustomer=ctrlcustomer.getAll();
            if (allcustomer == null) {
                return;
            }
            cmbCID.removeAllItems();
            for(CustomerDTO customer: allcustomer){
                cid=customer.getCid();
                cmbCID.addItem(cid);
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    private void loadItemCodes() {
        String code = null;
        try {
            ArrayList<ItemDTO> allitem=ctrlItem.getAll();
            if (allitem == null) {
                return;
            }
            cmbICode.removeAllItems();
            for(ItemDTO item: allitem){
                code=item.getICode();
                cmbICode.addItem(code);
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    private void loadBatchID(String code) {
        
         String bid = null;
         String icode = null;
         int qty = 0;
        try {
            ArrayList<BatchDTO> allbatch=ctrlBatch.getAll();
            if (allbatch == null) {
                return;
            }
            cmbBatch.removeAllItems();
            for(BatchDTO batch: allbatch){
                bid=batch.getBatchId();
                icode=batch.getiCode();
                qty=batch.getQtyOnHand();
                if(icode.matches(code)){
                    if(qty>0){
                        cmbBatch.addItem(bid);
                    }
                }
                   
               
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }

    private void loadOrderId() {
        String newID;
        try {
            newID = IDGenerator.getNewID("CustomerOrder", "OID", "CO");
            txtOrderID.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    private void ManageCustomer() {
         new ManageCustomer().setVisible(true);
    }

    private void loadKeyListener() {
         KeyboardFocusManager manger = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manger.addKeyEventPostProcessor(new KeyEventPostProcessor() {

            @Override
            public boolean postProcessKeyEvent(KeyEvent e) {
                if(e.getID()== KeyEvent.KEY_PRESSED){
                    switch(e.getKeyCode()){
                        case KeyEvent.VK_CONTROL:
                            ManageCustomer();break;
                        case KeyEvent.VK_ESCAPE:
                            Back();break;
                       
                        
                    }
                }
                return false;
            }
        });
    }

    private void Back() {
        this.dispose();
        tmrTime.stop();
    }

   private boolean Check(){
       
       String unit = txtUnit.getText();
       String dis = txtDiscount.getText();
       String qty = txtQTY.getText();
      
        
          if (dis.matches("[0-9]+")) {
                  if (qty.matches("[0-9]+")) {
          
                        return true;
                  } 
               
          }
         return false;  
    }

    private void pnlBack() {
       
        pnlBackPayment.setBackground(new Color(0,0,0,200));
         pnlBackPayment.setVisible(false);
         
    }

    private void loadPaymentID() {
         String newID;
        try {
            newID = IDGenerator.getNewID("CustomerPayment", "CPID", "CPID");
            txtPaymentID.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    private void setTime() {
         tmrTime=new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    
    }

    private void printReport() {
       try {
           
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(CustOrder.class.getResource("/edu/ijse/business_managment_system/jasper/CustomerBill.jasper"));
            
            HashMap<String, Object> parameters = new HashMap<>();
             parameters.put("FirstName", txtFName.getText());
             parameters.put("oid", txtOrderID.getText());
             parameters.put("Total", txtTotal.getText());
             parameters.put("Payment", txtPayment.getText());
             parameters.put("Balance", txtBalance.getText());
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport,parameters, new JRTableModelDataSource(tblOrder.getModel()));
            
            MyJasperView frmJasperViewer = new MyJasperView(filledReport);
            frmJasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(CustOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }

   
}
