/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.business_managment_system.view;

import edu.ijse.business_managment_system.controller.ControllerFactory;
import edu.ijse.business_managment_system.controller.custom.CustomerController;
import edu.ijse.business_managment_system.view.ViewCustomer;

import edu.ijse.business_managment_system.dto.CustomerDTO;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Happy Go Lucky
 */
public class ManageCustomer extends javax.swing.JFrame {

      private CustomerController ctrlCustomer;
    private DefaultTableModel dtmCustomer;
    private Timer tmrTime;
    
    public ManageCustomer() {
        ctrlCustomer = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
        
        initComponents();
        loadKeyListener();
        setTimer();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblAddNew = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblViewAll = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblbackCustOr = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Customers");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 420, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ecs");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 50, 20));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Back");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 30, 20));

        lblAddNew.setBackground(new java.awt.Color(0, 0, 0));
        lblAddNew.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAddNew.setForeground(new java.awt.Color(255, 255, 255));
        lblAddNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddNew.setText("Ctrl");
        lblAddNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddNew.setOpaque(true);
        lblAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddNewMouseClicked(evt);
            }
        });
        jPanel3.add(lblAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 20));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Add New Customer");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 20));

        lblViewAll.setBackground(new java.awt.Color(0, 0, 0));
        lblViewAll.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblViewAll.setForeground(new java.awt.Color(255, 255, 255));
        lblViewAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAll.setText("Home");
        lblViewAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblViewAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewAll.setOpaque(true);
        lblViewAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewAllMouseClicked(evt);
            }
        });
        jPanel3.add(lblViewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 50, 20));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Select");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 20));

        lblDelete.setBackground(new java.awt.Color(0, 0, 0));
        lblDelete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete.setText("Delete");
        lblDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDelete.setOpaque(true);
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        jPanel3.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 20));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Delete Customer");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 100, 20));

        lblUpdate.setBackground(new java.awt.Color(0, 0, 0));
        lblUpdate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Alt");
        lblUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUpdate.setOpaque(true);
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
        });
        jPanel3.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 20));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Update Customer details");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 140, 20));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Enter");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel28.setOpaque(true);
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 20));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("View All Customers");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 140, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 1280, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Last Name :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 100, 30));

        txtCID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 200, 30));

        txtFirst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 350, 30));

        txtLast.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 350, 30));

        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 470, 30));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 470, 30));

        txtNic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 350, 30));

        txtContact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 350, 30));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("xxx-xxxxxxx");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 70, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Email :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 120, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("NIC :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 100, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Address :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 100, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Contact Number :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 120, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("First Name :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Customer ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, 30));

        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 130, 1250, 535));

        lblbackCustOr.setBackground(new java.awt.Color(153, 0, 153));
        lblbackCustOr.setOpaque(true);
        jPanel1.add(lblbackCustOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1260, 570));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 204));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 290, 50));

        lblBack.setBackground(new java.awt.Color(102, 102, 102));
        lblBack.setOpaque(true);
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        Back();
        
    }//GEN-LAST:event_jLabel24MouseClicked

    private void lblAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewMouseClicked
     
        AddCustomer();
        
    }//GEN-LAST:event_lblAddNewMouseClicked

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked

        DeleteCustomer();
       	
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        
        UpdateCustomer();
        		
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblViewAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllMouseClicked
        ViewAllCustomer();
       
    }//GEN-LAST:event_lblViewAllMouseClicked

    private void txtCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIDActionPerformed
         String cid=txtCID.getText();
	try{
		CustomerDTO customer=ctrlCustomer.search(cid);
		if(customer!=null){
			txtFirst.setText(customer.getFisrtName());
			txtLast.setText(customer.getLastName());
                        txtNic.setText(customer.getNic());
			txtContact.setText(customer.getContact());
                        txtEmail.setText(customer.getEmail());
                        txtAddress.setText(customer.getAddress());
		}else{
			JOptionPane.showMessageDialog(ManageCustomer.this,"Customer not found...");
		}
		}catch(SQLException e){
			JOptionPane.showMessageDialog(ManageCustomer.this,e.getMessage());
		}catch(ClassNotFoundException e){
                    JOptionPane.showMessageDialog(ManageCustomer.this,e.getMessage());
		} catch (Exception ex) {	
                    Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }	
    }//GEN-LAST:event_txtCIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAddNew;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblViewAll;
    private javax.swing.JLabel lblbackCustOr;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtNic;
    // End of variables declaration//GEN-END:variables

    private void loadKeyListener() {
        KeyboardFocusManager manger = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manger.addKeyEventPostProcessor(new KeyEventPostProcessor() {

            @Override
            public boolean postProcessKeyEvent(KeyEvent e) {
                if(e.getID()== KeyEvent.KEY_PRESSED){
                    switch(e.getKeyCode()){
                        case KeyEvent.VK_CONTROL:
                            AddCustomer();break;
                        case KeyEvent.VK_ALT:
                            UpdateCustomer();break;
                         case KeyEvent.VK_DELETE:
                            DeleteCustomer();break;
                        case KeyEvent.VK_HOME:
                            ViewAllCustomer();break;
                        case KeyEvent.VK_ESCAPE:
                            Back();break;
                        
                    }
                }
                return false;
            }
        });
    }

    private void AddCustomer() {
        
          boolean isCheck=Check();
        if(isCheck){
        
            String cid=txtCID.getText();
            String first = txtFirst.getText();
            String last = txtLast.getText();
            String nic = txtNic.getText();
            String contact = txtContact.getText();
            String email = txtEmail.getText();
            String address = txtAddress.getText();

            CustomerDTO customerDTO = new CustomerDTO(cid,first,last,nic,contact,email,address);
            try{
                boolean isAdded=ctrlCustomer.add(customerDTO);
            if(isAdded){
                JOptionPane.showMessageDialog(ManageCustomer.this,"Customer Added Successfully");
            }
            } catch (SQLException ex) {
            String errorMsg;

            ImageIcon icon = new ImageIcon(this.getClass().getResource("/edu/ijse/business_managment_system/view/pics/error_icon.png"));

            switch (ex.getErrorCode()) {
                case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid Customer Id to proceed.";
                    break;
                default:
                    errorMsg = "Customer has been failed to add";
                    break;
                }
            }catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(ManageCustomer.this,e);
            } catch (Exception ex) {
                  Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
             JOptionPane.showMessageDialog(this, "Check Again, And Input Validate Data To Proceed", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
             
         
    }

    private void UpdateCustomer() {
        
         boolean isCheck=Check();
        if(isCheck){
            
                String cid=txtCID.getText();
                String first = txtFirst.getText();
                String last = txtLast.getText();
                String nic = txtNic.getText();
                String contact = txtContact.getText();
                String email = txtEmail.getText();
                String address = txtAddress.getText();
                CustomerDTO customerDTO=new CustomerDTO(cid,first,last,nic,contact,email,address);
                try{
                    boolean isUpdate=ctrlCustomer.update(customerDTO);
                if(isUpdate){
                    JOptionPane.showMessageDialog(ManageCustomer.this," Customer Update Success...");
                }else{
                    JOptionPane.showMessageDialog(ManageCustomer.this,"Customer Update Fail");
                }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(ManageCustomer.this,e.getMessage());
                }catch(ClassNotFoundException e){
                    JOptionPane.showMessageDialog(ManageCustomer.this,e.getMessage());
                } catch (Exception ex) {				
                      Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
             JOptionPane.showMessageDialog(this, "Check Again, And Input Validate Data To Proceed. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void DeleteCustomer() {
         String cid=txtCID.getText();
        try{
	boolean isDeleted=ctrlCustomer.delete(cid);
	if(isDeleted){
            JOptionPane.showMessageDialog(ManageCustomer.this," Customer Deleted...");
	}else{
            JOptionPane.showMessageDialog(ManageCustomer.this,"Customer not found...");
	}
	}catch(SQLException e){
		System.out.println(e.getMessage());
	}catch(ClassNotFoundException e){
		System.out.println(e.getMessage());
	} catch (Exception ex) {		
              Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
          }	
    }

    private void ViewAllCustomer() {
         new ViewCustomer().setVisible(true);
    }

    private void Back() {
        this.dispose();
        tmrTime.stop();
    }

   
    
    private boolean Check(){
       
       String first = txtFirst.getText();
       String last = txtLast.getText();
       String contact = txtContact.getText();
       String email = txtEmail.getText();
        String address = txtAddress.getText();
        String nic = txtNic.getText();
        
          if (first.matches("[A-Za-z ]+")) {
              if (last.matches("[A-Za-z ]+")) {
                  if (contact.matches("\\d{3}\\-\\d{7}")) {
                      if (email.matches("^[A-za-z]([A-Za-z0-9]+\\.)*[A-Za-z0-9]+@[A-Za-z0-9]+([A-Za-z0-9]+\\.)*(\\.[A-Za-z0-9]+)+$")) {
                               if (nic.matches("\\b\\d{9}[Vv]\\b")) {
                                    return true;
                               }
                          
                      }
                      
                  }
                  
              }  
          }
         return false;
          
    }

    private void setTimer() {
         tmrTime=new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    }
}
