/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.business_managment_system.view;

import edu.ijse.business_managment_system.controller.ControllerFactory;
import edu.ijse.business_managment_system.controller.custom.BrandController;
import edu.ijse.business_managment_system.controller.custom.ItemController;
import edu.ijse.business_managment_system.controller.custom.SupplierController;
import edu.ijse.business_managment_system.controller.custom.SupplierOrderController;
import edu.ijse.business_managment_system.dto.BrandDTO;
import edu.ijse.business_managment_system.dto.ItemDTO;
import edu.ijse.business_managment_system.dto.SupplierDTO;
import edu.ijse.business_managment_system.dto.SupplierOrderDTO;
import edu.ijse.business_managment_system.dto.SupplierOrderDetailDTO;
import edu.ijse.business_managment_system.idgenerator.IDGenerator;
import edu.ijse.business_managment_system.jasper.MyJasperView;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;


/**
 *
 * @author Happy Go Lucky
 */
public class SupOrder extends javax.swing.JFrame {
    
   private ItemController ctrlItem;
    private SupplierController ctrlSupplier;
    private BrandController ctrlBrand;
    private SupplierOrderController ctrlSupplierOrder;
     private Timer tmrTime;
   

    /**
     * Creates new form SupOrder
     */
    public SupOrder() {
        
        ctrlItem = (ItemController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEM);
        ctrlSupplier = (SupplierController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUPPLIER);
        ctrlBrand = (BrandController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BRAND);
       ctrlSupplierOrder = (SupplierOrderController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUPPLIER_ORDER);
        
        initComponents();
        loadSID();
        loadCode();
        setOrderDate();
        loadOrderId();
        loadKeyListener();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtQTY = new javax.swing.JTextField();
        txtOrderID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtSupName = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        txtModel = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCart1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbSid = new javax.swing.JComboBox();
        cmbCode = new javax.swing.JComboBox();
        lblRemove = new javax.swing.JLabel();
        lblMakeOrder = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblbackCustOr = new javax.swing.JLabel();
        pnlTime = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Make supplier Order");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 420, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Ctrl");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 20));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("View Stock");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, 20));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ecs");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 50, 20));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Back");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 30, 20));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Enter");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel22.setOpaque(true);
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 20));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Select");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 1280, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 1260, 10));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 100, 30));

        txtQTY.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQTYActionPerformed(evt);
            }
        });
        jPanel1.add(txtQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 170, 30));

        txtOrderID.setEditable(false);
        txtOrderID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 180, 30));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 180, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 1260, 10));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Brand :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 100, 30));

        txtSupName.setEditable(false);
        txtSupName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 450, 30));

        txtBrand.setEditable(false);
        txtBrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        jPanel1.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 180, 30));

        tblOrder.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Brand", "Model", "Order Qty"
            }
        ));
        jScrollPane3.setViewportView(tblOrder);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 1220, 160));

        txtModel.setEditable(false);
        txtModel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        jPanel1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 450, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 1260, 10));

        lblCart1.setBackground(new java.awt.Color(51, 255, 0));
        lblCart1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblCart1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCart1.setText("Add To Order");
        lblCart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        lblCart1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCart1.setOpaque(true);
        lblCart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCart1MouseClicked(evt);
            }
        });
        jPanel1.add(lblCart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 180, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Order QTY :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 100, 30));

        cmbSid.setEditable(true);
        cmbSid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbSid.setMaximumRowCount(100);
        cmbSid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        cmbSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSidActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 180, 30));

        cmbCode.setEditable(true);
        cmbCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbCode.setMaximumRowCount(100);
        cmbCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        cmbCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 180, 30));

        lblRemove.setBackground(new java.awt.Color(255, 0, 0));
        lblRemove.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Remove");
        lblRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRemove.setOpaque(true);
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
        });
        jPanel1.add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 60, 20));

        lblMakeOrder.setBackground(new java.awt.Color(51, 255, 0));
        lblMakeOrder.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblMakeOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMakeOrder.setText("Make Order");
        lblMakeOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        lblMakeOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMakeOrder.setOpaque(true);
        lblMakeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakeOrderMouseClicked(evt);
            }
        });
        jPanel1.add(lblMakeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, 180, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Model :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 100, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("ICode :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 100, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("SID :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 100, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Date :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 100, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Order ID :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 100, 30));

        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, 1270, 535));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New supplier Order");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 280, 30));

        lblbackCustOr.setBackground(new java.awt.Color(153, 0, 153));
        lblbackCustOr.setOpaque(true);
        jPanel1.add(lblbackCustOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1280, 570));

        pnlTime.setBackground(new java.awt.Color(255, 255, 255));
        pnlTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 204));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlTime.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jPanel1.add(pnlTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 290, 50));

        lblBack.setBackground(new java.awt.Color(102, 102, 102));
        lblBack.setOpaque(true);
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
         Back();
        
    }//GEN-LAST:event_jLabel24MouseClicked

    private void txtSupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupNameActionPerformed

    private void txtQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQTYActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void cmbSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSidActionPerformed
        
         try {
            String sid=(String)cmbSid.getSelectedItem();
            SupplierDTO supplier=ctrlSupplier.search(sid);
            txtSupName.setText(supplier.getName());
        } catch (Exception ex) {
            //Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbSidActionPerformed

    private void cmbCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodeActionPerformed
        
        try {
            String code=(String)cmbCode.getSelectedItem();
            ItemDTO item=ctrlItem.search(code);
            String bid= (item.getBrand());
            txtModel.setText(item.getModel());
            BrandDTO brand = ctrlBrand.search(bid);
            txtBrand.setText(brand.getBrandName());
        } catch (Exception ex) {
           // Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_cmbCodeActionPerformed

    private void lblCart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCart1MouseClicked
         
         boolean isCheck=Check();
            if(isCheck){
        
                String itemCode=(String)cmbCode.getSelectedItem();
                    DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
                    String brand=txtBrand.getText();
                    String model=txtModel.getText();
                    int orderQty=Integer.parseInt(txtQTY.getText());


                        for(int i=0;i<dtm.getRowCount();i++){
                            String code=(String)dtm.getValueAt(i,0);
                            if(itemCode.equals(code)){
                                int qty=(int)dtm.getValueAt(i,3);	
                                orderQty+=qty;
                                dtm.removeRow(i);	
                            }
                        }


                        Object[] rowData={itemCode,brand,model,orderQty};	
                        dtm.addRow(rowData);
                        
                        txtQTY.setText("");
					
           }else{
                 JOptionPane.showMessageDialog(this, "Check Again, And Input Validate Data To Proceed. ", "Error", JOptionPane.ERROR_MESSAGE);
            } 
    }//GEN-LAST:event_lblCart1MouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked
        DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
				int index=tblOrder.getSelectedRow();
				dtm.removeRow(index);
				
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblMakeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeOrderMouseClicked
      
        DefaultTableModel dtm=(DefaultTableModel)tblOrder.getModel();
        String orderId=txtOrderID.getText();
        String date = txtDate.getText();
        String supplier = (String) cmbSid.getSelectedItem();
        
        SupplierOrderDTO supplierOrderDTO = new SupplierOrderDTO(orderId,supplier,date);
        ArrayList<SupplierOrderDetailDTO> allSupplierOrderDetails = new ArrayList<>();
        
        for(int i=0;i<dtm.getRowCount();i++){
            SupplierOrderDetailDTO supplierOrderDetail = new SupplierOrderDetailDTO(
                    txtOrderID.getText(), 
                    dtm.getValueAt(i, 0).toString(),
                    Integer.parseInt(dtm.getValueAt(i, 3).toString()));
                    
            allSupplierOrderDetails.add(supplierOrderDetail);
        }
        
        try {
            boolean result = ctrlSupplierOrder.add(supplierOrderDTO, allSupplierOrderDetails);
            if (result){
                JOptionPane.showMessageDialog(this, "Order has been successfully placed","Success",JOptionPane.INFORMATION_MESSAGE);
                printReport();
                loadOrderId();
                txtQTY.setText("");
                 dtm.setRowCount(0);
            }else{
                JOptionPane.showMessageDialog(this, "Failed to place the order", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to place the order", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblMakeOrderMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
       ViewAllStock();
        
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCode;
    private javax.swing.JComboBox cmbSid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCart1;
    private javax.swing.JLabel lblMakeOrder;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblbackCustOr;
    private javax.swing.JPanel pnlTime;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtSupName;
    // End of variables declaration//GEN-END:variables

    private void loadSID() {
        
        String sid = null;
        try {
            ArrayList<SupplierDTO> allsupplier=ctrlSupplier.getAll();
            if (allsupplier == null) {
                return;
            }
            cmbSid.removeAllItems();
            for(SupplierDTO supplier: allsupplier){
                sid=supplier.getSid();
                cmbSid.addItem(sid);
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }

    private void loadCode() {
         String code = null;
        try {
            ArrayList<ItemDTO> allItems=ctrlItem.getAll();
            if (allItems == null) {
                return;
            }
            cmbCode.removeAllItems();
            for(ItemDTO item: allItems){
                code=item.getICode();
                cmbCode.addItem(code);
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    private void setOrderDate() {
       java.util.Date d1=new java.util.Date();
		SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
		String formatDate=df.format(d1);
		txtDate.setText(formatDate);
    }

    private void loadOrderId() {
       String newID;
        try {
            newID = IDGenerator.getNewID("SupplierOrder", "SOID", "SO");
            txtOrderID.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    private void Back() {
        this.dispose();
        tmrTime.stop();
    }

    private void ViewAllStock() {
        new ViewStock().setVisible(true);
    }
    
     private void loadKeyListener() {
         KeyboardFocusManager manger = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manger.addKeyEventPostProcessor(new KeyEventPostProcessor() {

            @Override
            public boolean postProcessKeyEvent(KeyEvent e) {
                if(e.getID()== KeyEvent.KEY_PRESSED){
                    switch(e.getKeyCode()){
                        case KeyEvent.VK_CONTROL:
                            ViewAllStock();break;
                        case KeyEvent.VK_ESCAPE:
                            Back();break;
                        
                    }
                }
                return false;
            }
        });
    }
     
      private boolean Check(){
       
       
       String qty = txtQTY.getText();
      
        
          
               
                  if (qty.matches("[0-9 ]+")) {
          
                        return true;
                  } 
                
          
         return false;  
    }

    private void setTime() {
         tmrTime=new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh: mm: ss");
                lblTime.setText(sdf.format(dt));
            }

        } );
         tmrTime.start();
    }

    private void printReport() {
         try {
           
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(SupOrder.class.getResource("/edu/ijse/business_managment_system/jasper/SupplierOrder.jasper"));
            
            HashMap<String, Object> parameters = new HashMap<>();
             parameters.put("SupplierName", txtSupName.getText());
            parameters.put("OID", txtOrderID.getText());
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport,parameters, new JRTableModelDataSource(tblOrder.getModel()));
            
            MyJasperView frmJasperViewer = new MyJasperView(filledReport);
            frmJasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(SupOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
